### ISSUE TITLE
How to make it fail on warning?

### ISSUE THREAD

**Issue by Anoncheg1** [riscy/melpazoid#38]
That is how I use it:
https://github.com/Anoncheg1/selected-window-contrast/blob/main/.github/workflows/melpazoid.yml

```yaml
env:
          LOCAL_REPO: ${{ github.workspace }}
          # RECIPE is your recipe as written for MELPA:
          RECIPE: (selected-window-contrast :fetcher github :repo "Anoncheg1/selected-window-contrast")
          # set this to false (or remove it) if the package isn't on MELPA:
          # EXIST_OK: false
        run: echo $GITHUB_REF && make -C ~/melpazoid
```

What should I set to make it error at any warning and crash Github Action run?

What customizations are possible?
