### ISSUE TITLE
Melpazoid error: Invalid read syntax: "expected )", 1213, 26

### ISSUE THREAD

**Issue by jamescherti** [riscy/melpazoid#40]
Melpazoid has been experiencing issues, resulting in a failed load due to syntax errors. The compilation process terminated with exit code 255.
```
  eval-buffer(#<buffer  *load*> nil "/workspace/pkg/melpazoid.el" nil t)
  load-with-code-conversion("/workspace/pkg/melpazoid.el" "/workspace/pkg/melpazoid.el" nil t)
  command-line-1(("--load=melpazoid.el"))
  command-line()
  normal-top-level()
Stderr output while compiling/loading:

Invalid read syntax: "expected )", 1213, 26
make[1]: *** [Makefile:13: test] Error 255

⸺ Package and license:
- Avoid `:branch` in recipes except in unusual cases
- Please specify `:fetcher` before `:repo` in your recipe
- Prefer equivalent recipe: `(compile-angel :fetcher github :repo "jamescherti/compile-angel.el" :branch "develop")`
- Reminder: ensure GitHub release 1.0.5 is up-to-date with your current code and `Package-Version`
- pkg/compile-angel.el: GNU General Public License v3.0 or later
- Repository: GNU General Public License v3.0
make: *** [Makefile:8: run] Error 2
make: Leaving directory '/home/runner/melpazoid'
```

More information:
- GitHub actions job: https://github.com/jamescherti/compile-angel.el/actions/runs/13530548103/job/37811449737

The GitHub actions melpazoid.yml:
```yaml
name: melpazoid
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install
        run: |
          rm -fr ~/.emacs.d
          python -m pip install --upgrade pip
          sudo apt-get install emacs && emacs --version
          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
          pip install ~/melpazoid
          cat ~/melpazoid/melpazoid/melpazoid.el
      - name: Run
        env:
          LOCAL_REPO: ${{ github.workspace }}
          # set this to false (or remove it) if the package isn't on MELPA:
          RECIPE: (compile-angel :fetcher github :repo "jamescherti/compile-angel.el" :branch "${{ github.ref_name }}")
          EXIST_OK: true
        run: echo $GITHUB_REF && make -C ~/melpazoid
```
